#Spring Boot Config

#端口
server:
  port: 8080

#文件上传路径
file-upload-path: E:/test

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: ENC(/OhVqDVHTMz9nUJnXKMiP7jZTlPDwAyF/WRnR3faUw5vIKzpn8fWhNiwetnRZDIm/Eyt5EUXDR0UEBieAy8irO9CjmncVoYgvYsggRCZN6SO//ICWn1QsGWUjfDZEs1XHctfwSvtYSjt4JDlOAn+cw1==)
    username: ENC(MSsag8xmuJE9egaB5BjrVA1==)
    password:  ENC(+XMXZSgfC+3zQCKakR+pNbf2ixuTgKbU1)
  mail:
    host: smtp.163.com
    username: fanshuye1304@163.com
    password: fanshuye1304
  freemarker:
    suffix: .html
    request-context-attribute: request
    charset: UTF-8
  aop:
    proxy-target-class: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true

#MyBatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xiaobingby.sys.entity;com.xiaobingby.oss.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    meta-object-handler: com.xiaobingby.config.mybatis.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

#logging
logging:
  level: debug